# Generated by Django 5.0.1 on 2024-02-20 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photaTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=200)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, verbose_name='Date Recorded')),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.ImageField(default=None, upload_to='')),
                ('banner', models.ImageField(default=None, upload_to='')),
                ('cqt_single_gzip_file', models.FileField(default=None, null=True, upload_to='photaMusic/static/photaMusic/cqt_single_gzip/')),
                ('cqt_single_gzip_header', models.FileField(default=None, null=True, upload_to='photaMusic/static/photaMusic/cqt_single_gzip/')),
                ('file', models.FileField(upload_to='photaMusic/photaTracks/')),
                ('img', models.ImageField(max_length=200, upload_to='photaMusic/photaTracks/img/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='publicTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=200)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, verbose_name='Date Recorded')),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.ImageField(default=None, upload_to='')),
                ('banner', models.ImageField(default=None, upload_to='')),
                ('cqt_single_gzip_file', models.FileField(default=None, null=True, upload_to='photaMusic/static/photaMusic/cqt_single_gzip/')),
                ('cqt_single_gzip_header', models.FileField(default=None, null=True, upload_to='photaMusic/static/photaMusic/cqt_single_gzip/')),
                ('expiry', models.DateTimeField(default=datetime.datetime(2024, 2, 20, 6, 35, 36, 698579, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time')),
                ('file', models.FileField(upload_to='photaMusic/publicTracks/')),
                ('img', models.ImageField(max_length=200, upload_to='photaMusic/publicTracks/img/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
