# Generated by Django 2.1.3 on 2019-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photaTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirey', models.DateTimeField(verbose_name='Expirey Time')),
                ('date_published', models.DateTimeField(verbose_name='Date Published')),
                ('date_recorded', models.DateTimeField(verbose_name='Date Published')),
                ('track_name', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('fileAudio', models.FileField(upload_to='photaMusic/static/photaMusic/photaTracks/')),
                ('img', models.ImageField(max_length=200, upload_to='photaMusic/static/photaMusic/photaTracks/img/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='publicTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirey', models.DateTimeField(verbose_name='Expirey Time')),
                ('date_published', models.DateTimeField(verbose_name='Date Published')),
                ('date_recorded', models.DateTimeField(verbose_name='Date Published')),
                ('track_name', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('fileAudio', models.FileField(upload_to='photaMusic/static/photaMusic/publicTracks/')),
                ('img', models.ImageField(max_length=200, upload_to='photaMusic/static/photaMusic/publicTracks/img/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='audio',
        ),
    ]
