# Generated by Django 2.1.3 on 2019-04-22 23:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0002_auto_20190422_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photatrack',
            name='expirey',
        ),
        migrations.RemoveField(
            model_name='publictrack',
            name='expirey',
        ),
        migrations.AddField(
            model_name='photatrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 23, 52, 47, 800249, tzinfo=utc), verbose_name='Expiry Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photatrack',
            name='file_audio',
            field=models.FileField(default=datetime.datetime(2019, 4, 22, 23, 52, 58, 646788, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 23, 53, 3, 430555, tzinfo=utc), verbose_name='Expiry Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publictrack',
            name='file_audio',
            field=models.FileField(default=datetime.datetime(2019, 4, 22, 23, 53, 18, 468492, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
