# Generated by Django 2.1.3 on 2019-04-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0003_auto_20190422_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photatrack',
            name='fileAudio',
        ),
        migrations.RemoveField(
            model_name='publictrack',
            name='fileAudio',
        ),
        migrations.AlterField(
            model_name='photatrack',
            name='file_audio',
            field=models.FileField(upload_to='photaMusic/static/photaMusic/photaTracks/'),
        ),
        migrations.AlterField(
            model_name='publictrack',
            name='file_audio',
            field=models.FileField(upload_to='photaMusic/static/photaMusic/publicTracks/'),
        ),
    ]
