# Generated by Django 2.1.3 on 2019-04-26 03:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0005_auto_20190425_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photatrack',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='publictrack',
            name='date_published',
        ),
        migrations.AddField(
            model_name='photatrack',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Upload Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publictrack',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Upload Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 13, 55, 16, 228133), verbose_name='Expiry Time'),
        ),
    ]
