# Generated by Django 2.1.3 on 2019-04-29 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0008_auto_20190429_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photaaudiofile',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='publicaudiofile',
            name='filename',
        ),
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 15, 3, 52, 682046), verbose_name='Expiry Time'),
        ),
    ]
