# Generated by Django 2.1.3 on 2019-04-29 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0009_auto_20190429_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 15, 4, 36, 278121), verbose_name='Expiry Time'),
        ),
    ]
