# Generated by Django 2.1.3 on 2019-04-29 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0010_auto_20190429_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 15, 5, 12, 998282), verbose_name='Expiry Time'),
        ),
    ]
