# Generated by Django 2.1.3 on 2019-04-29 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0011_auto_20190429_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 17, 15, 29, 109839), verbose_name='Expiry Time'),
        ),
    ]
