# Generated by Django 2.2 on 2019-04-29 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0012_auto_20190429_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 17, 32, 25, 838700), verbose_name='Expiry Time'),
        ),
    ]
