# Generated by Django 2.2 on 2019-04-30 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0014_auto_20190430_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 1, 57, 7, 739672), verbose_name='Expiry Time'),
        ),
    ]
