# Generated by Django 2.2 on 2019-05-01 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0016_auto_20190430_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 2, 3, 19, 423700), verbose_name='Expiry Time'),
        ),
    ]
