# Generated by Django 2.2 on 2019-05-03 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0023_auto_20190503_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 41, 37, 485574), verbose_name='Expiry Time'),
        ),
    ]
