# Generated by Django 2.2 on 2019-05-03 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0024_auto_20190503_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 42, 30, 855008), verbose_name='Expiry Time'),
        ),
    ]
