# Generated by Django 2.2 on 2019-05-03 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0031_auto_20190503_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 15, 53, 23, 940102), verbose_name='Expiry Time'),
        ),
    ]
