# Generated by Django 2.2 on 2019-05-03 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0033_auto_20190503_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 16, 5, 18, 198795), verbose_name='Expiry Time'),
        ),
    ]
