# Generated by Django 2.2 on 2019-05-03 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0037_auto_20190503_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 16, 56, 31, 571048), verbose_name='Expiry Time'),
        ),
    ]
