# Generated by Django 2.2 on 2019-05-03 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0039_auto_20190503_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 17, 4, 27, 748667), verbose_name='Expiry Time'),
        ),
    ]
