# Generated by Django 2.2 on 2019-05-03 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0041_auto_20190503_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 17, 19, 51, 950494), verbose_name='Expiry Time'),
        ),
    ]
