# Generated by Django 2.2 on 2019-05-05 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0042_auto_20190503_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 5, 22, 58, 59, 74360), verbose_name='Expiry Time'),
        ),
    ]
