# Generated by Django 2.2 on 2019-05-07 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0043_auto_20190505_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 21, 26, 54, 523854), verbose_name='Expiry Time'),
        ),
    ]
