# Generated by Django 2.2 on 2019-05-07 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0044_auto_20190507_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 1, 34, 8, 74357), verbose_name='Expiry Time'),
        ),
    ]
