# Generated by Django 2.2 on 2019-05-07 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0045_auto_20190507_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 2, 6, 24, 686532), verbose_name='Expiry Time'),
        ),
    ]
