# Generated by Django 2.2 on 2019-05-07 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0047_auto_20190507_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 9, 9, 13, 447154), verbose_name='Expiry Time'),
        ),
    ]
