# Generated by Django 2.2 on 2019-05-07 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0048_auto_20190507_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 9, 12, 16, 120238), verbose_name='Expiry Time'),
        ),
    ]
