# Generated by Django 2.2 on 2019-05-08 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0051_auto_20190507_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 14, 10, 8, 597208), verbose_name='Expiry Time'),
        ),
    ]
