# Generated by Django 2.2 on 2019-05-09 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0053_auto_20190509_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 17, 16, 53, 843431), verbose_name='Expiry Time'),
        ),
    ]
