# Generated by Django 2.2 on 2019-05-09 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0054_auto_20190509_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 17, 17, 56, 836168), verbose_name='Expiry Time'),
        ),
    ]
