# Generated by Django 2.2 on 2019-05-10 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaMusic', '0055_auto_20190509_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictrack',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 16, 12, 58, 547753), verbose_name='Expiry Time'),
        ),
    ]
