# Generated by Django 2.1.3 on 2019-01-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subpagebubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('templatePath', models.CharField(max_length=200, unique=True)),
                ('pageapp', models.CharField(choices=[('photaChristianity', 'Christian'), ('photaPhysics', 'Physicist')], max_length=2)),
            ],
        ),
    ]
