# Generated by Django 2.1.3 on 2019-01-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaHome', '0003_auto_20190127_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpagebubble',
            name='template_path',
            field=models.CharField(max_length=200),
        ),
    ]
