# Generated by Django 2.1.3 on 2019-01-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photaHome', '0004_auto_20190127_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpagebubble',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('h', 'Hidden')], default='d', max_length=1),
        ),
    ]
